language: go

go:
  - 1.11.x

compiler:
  - gcc

services:
  - mysql

before_install:
  - GO111MODULE=on go mod vendor
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;"
  - sudo mysql -e "grant all privileges on test.* to testuser@'%' identified by '123456';FLUSH PRIVILEGES;"
  - mysql -e 'use test; CREATE TABLE `label` ( `id` int(11) unsigned NOT NULL COMMENT "the primary key", `name` varchar(64) NOT NULL DEFAULT "unknown" COMMENT "name", `age` tinyint(4) NOT NULL DEFAULT "0" COMMENT "age", `deleted` bit(1) NOT NULL , `note` varchar(255) DEFAULT NULL COMMENT "desc", `created` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT "created time", `updated` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT "last updated", `personcol` float(5,3) unsigned DEFAULT NULL, `personcol2` double(6,3) DEFAULT NULL, `personcol1` decimal(3,2) DEFAULT NULL, `charcol` char(45) DEFAULT NULL, `textCol` mediumtext, `bitcol` bit(19) DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `idx_id` (`id`), KEY `idx_name` (`name`)) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT="table for person information";'

script:
  - go build .
  - go test ./...  -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)